### ISSUE TITLE
intro restarted if step into input

### ISSUE THREAD

**Issue by rmpt** [heminei/jquery-hemi-intro#3]
Correcting my initial issue, I thougth that if some of the elements require a scroll in the page, after the last step the intro is restarted.
But the real issue is about input elements. I've changed the selector to the input wrapper and now it seems to work fine.

**Comment by heminei** [comment]
Hi,
Please, send me demo url.

**Comment by CaptainKarma** [comment]
I had the same problem, seems to be something strange with targeting IDs that are input fields in forms would cause a page reload.  If I took out the targeting of the input was all ok for the other elements.

Due to time constraints I couldn't delve into this further and had to switch to the hopscotch tour guide.
Real shame as the UI of your plugin is so great!

**Comment by heminei** [comment]
@CaptainKarma Please send me a demo.

**Comment by CaptainKarma** [comment]
https://pastebin.com/4YHAW2HJ

Please find linked.  I removed it to the bare basics

Cheers

**Comment by heminei** [comment]
Thanks. The bug is fixed. You can download the last version.
